version: '3.9'
services:
  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    restart: always
    networks:
      - prometheus
    ports:
      - '9090:9090'
    #environment:
    #  PROMETHEUS_HOME: C:/git-hub/spring-custom-metric/prometheus
    volumes:
      - 'C:\git-hub\spring-custom-metrics\prometheus\:/etc/prometheus/'
  grafana:
    image: 'grafana/grafana'
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - prometheus
  camel-ms:
    build: ../
    container_name: camel-ms
    ports:
      - '8080:8080'
    environment:
      - SPRING_CONFIG_LOCATION=/config/
    volumes:
      - 'C:/git-hub/spring-custom-metrics/config/:/config/'
    networks:
      - prometheus
networks:
  prometheus:
    external: false