version: '3'
services:
  prometheus:
    image: 'prom/prometheus'
    restart: always
    networks:
      - prometheus
    ports:
      - '9090:9090'
    #environment:
    #  PROMETHEUS_HOME: C:/git-hub/spring-custom-metric/prometheus
    volumes:
      - 'C:\git-hub\spring-custom-metrics\prometheus\:/etc/prometheus/'
  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    networks:
      - prometheus
networks:
  prometheus:
    external: false